name: PyPI Publisher

on:
  push:
    tags:
      - '*'

jobs:
  Publish-to-PyPI:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Install Dependencies
        run: pip install wheel
      -
        name: Build Distribution packages
        run: python setup.py sdist bdist_wheel
      -
        name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        if: startsWith(github.ref, 'refs/tags/')
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}

